### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AlphaKR93** [PrismarineTeam/PrismarineManager#2]
- [x] Gradle 자동 업데이트 추가
   - [x] Gradle 자동 업데이트 구문 제작
      - [x] 추가
   - [x] Gradle 업데이트 확인 구문 제작
      - [x] 추가
   - [x] 일반 Paper, Pufferfish, Purpur jobs에 추가
   - [x] 전용 Job 생성

**Comment by AlphaKR93** [comment]
- [ ] 자동 빌드 업스트림 추가
